# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 11:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr',
            name='login',
        ),
        migrations.AlterField(
            model_name='usr',
            name='username',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Adres e-mail'),
        ),
    ]
