# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankieta_model',
            name='data_zakonczenia',
            field=models.DateField(default='%d-%m-%Y'),
        ),
    ]
