# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0006_auto_20170313_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ankieta_model',
            new_name='AnkietaModel',
        ),
    ]
