# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0007_auto_20170313_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='id_ankiety',
            new_name='ankieta',
        ),
    ]
