# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0008_auto_20170314_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='id_Usr',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='id_wyboru',
            new_name='wybor',
        ),
    ]
