# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0009_auto_20170314_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='Usr',
        ),
    ]
