# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ankieta', '0010_auto_20170314_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('wybor', 'Usr')]),
        ),
    ]
