# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0011_auto_20170321_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
