# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0014_ankietamodel_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
