# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0016_ankietamodel_data_w'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankietamodel',
            name='data_w',
            field=models.DateField(default=datetime.datetime(2017, 3, 30, 11, 31, 1, 278002)),
        ),
    ]
