# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0024_auto_20170323_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankietamodel',
            name='data_w',
            field=models.DateField(),
        ),
    ]
