# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 11:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0026_auto_20170328_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankietamodel',
            name='data_w',
            field=models.DateField(default=datetime.datetime(2017, 4, 4, 11, 1, 21, 516006)),
        ),
    ]
