# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0027_auto_20170328_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankietamodel',
            name='data_w',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 10, 10, 32, 215785)),
        ),
    ]
